#!/usr/bin/env bash
#configure nginx server so that /redirect_me is redirecting to another page

sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee  /var/www/html/index.nginx-debian.html
sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
